# jwt(json web token)
# time is 30 min
jwt:
  signKey: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
  expireTimeAsSec: 1800000
  #expireTimeAsSec: 1800

server:
  port: 8888
  servlet:
    context-path: /fongff

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #基本属性
    url: jdbc:mysql://localhost:3306/fongff?useSSL=true&serverTimezone=Asia/Taipei&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20

  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  aop:
    auto: true
    proxy-target-class: true

  servlet:
    multipart:
#      max-file-size: 10Mb
#      max-request-size: 100Mb

logging:
  level:
    cloudtu: DEBUG


#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.wip.model

swagger:
  show: true
#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  retrunPageInfo: check


file:
  path: /data/tomcat/webapps/file
  realPath: http://34.81.176.39:8081/file
news:
  defaultPath: http://34.81.176.39:8081/file/newEvent-bg.jpg