spring:
  profiles:
    active: dev

  #解决Spring Boot集成JPA的Column注解命名字段会自动生成下划线的问题（命名规则）
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  aop:
    auto: true
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    cloudtu: DEBUG

swagger:
  show: true
#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  retrunPageInfo: check


file:
  path: /data/tomcat/webapps/file
  realPath: http://34.81.110.243:8081/file
news:
  defaultPath: http://34.81.110.243:8081/file/newEvent-bg.jpg